### ISSUE TITLE
TST: Use `cmocka` for testing

### ISSUE THREAD

**Issue by HaoZeke** [HaoZeke/OpenBLAS#11]
The current `ctest` and others are a slightly nightmarish set of `goto` riddled manual tests, would be nicer to use `cmocka`.

**Comment by rgommers** [comment]
This seems like the kind of thing to avoid doing separately from the main OpenBLAS project?

It sounds like a useful upgrade in principle, not clear though if it's needed for any of the work here?

**Comment by HaoZeke** [comment]
Yup, definitely not needed for the `meson` work; just came up when I went over some of tests to make sure they fail instead of printing failure and reporting success. Will reopen later in an expanded form on upstream.
